### ISSUE TITLE
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(54 bytes read)', IncompleteRead

### ISSUE THREAD

**Issue by slideup-benni** [jepayne1138/PTCAccount#10]
Hi,

i'll get

```
Traceback (most recent call last):
  File "/usr/local/bin/ptc", line 9, in <module>
    load_entry_point('PTCAccount==v1.2.1', 'console_scripts', 'ptc')()
  File "/usr/local/lib/python2.7/dist-packages/ptcaccount/console.py", line 45, in entry
    args.username, args.password, args.email, args.email_tag
  File "/usr/local/lib/python2.7/dist-packages/ptcaccount/accountcreator.py", line 379, in random_account
    try_username, password, try_email
  File "/usr/local/lib/python2.7/dist-packages/ptcaccount/accountcreator.py", line 226, in create_account
    resp_code=200
  File "/usr/local/lib/python2.7/dist-packages/ptcaccount/accountcreator.py", line 84, in request
    resp = self.send(prepped)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(54 bytes read)', IncompleteRead(54 bytes read))
```

when i run

ptc -u **\* -p **\* -e ***

what can i do?

**Comment by slideup-benni** [comment]
or that:

```
Traceback (most recent call last):
  File "/usr/local/bin/ptc", line 9, in <module>
    load_entry_point('PTCAccount==v1.2.1', 'console_scripts', 'ptc')()
  File "/usr/local/lib/python2.7/dist-packages/ptcaccount/console.py", line 45, in entry
    args.username, args.password, args.email, args.email_tag
  File "/usr/local/lib/python2.7/dist-packages/ptcaccount/accountcreator.py", line 379, in random_account
    try_username, password, try_email
  File "/usr/local/lib/python2.7/dist-packages/ptcaccount/accountcreator.py", line 226, in create_account
    resp_code=200
  File "/usr/local/lib/python2.7/dist-packages/ptcaccount/accountcreator.py", line 84, in request
    resp = self.send(prepped)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 669, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
```

**Comment by eXeLe** [comment]
I've got the same problem:
`requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(54 bytes read)', IncompleteRead(54 bytes read))`

**Comment by rrouene** [comment]
I had the same problem.
I did:
pip install git+https://github.com/jepayne1138/PTCAccount.git@v1.2.1 --upgrade

Working now!

Edit: Not working anymore. Seems to be coming from niantic's servers..

**Comment by CraftedFury** [comment]
Same problem here.
