### ISSUE TITLE
Problems running ur script

### ISSUE THREAD

**Issue by ghost** [jepayne1138/PTCAccount#2]
I try to run ur script on command prompt and double clicking it but its not working, can u make a video or a instructions please?

When i double click it, automatically close its and i cant see the error

**Comment by ghost** [comment]
Im Using python 2.7

**Comment by jepayne1138** [comment]
I'm not sure what you are clicking on so I'm not exactly sure where to start.

Open your terminal (Linux or Mac) or cmd (Windows) and navigate to where you want to install the program.  (If you wish to use a virtualenv so as to globally install the dependencies, do that now, but its not required to install.)  Follow the installation instructions in the README, specifically run:

```
pip install git+https://github.com/jepayne1138/PTCAccount.git@v1.1.1
```

This installation will create the "ptc" command.  Run the program by just typing:

```
ptc
```

I didn't create any entry point by running a specific file, so there currently isn't a way of just running it by double clicking on any file.

After running ptc, if you still have errors (not unlikely, as this isn't tested as thoroughly as it should be), could you please copy the Traceback message from the terminal and paste it here, and include what version of Python you're using (2.7 in this case) and what operating system you're using?  This will help me figure out any issues.

**Comment by zikphil** [comment]
`⋊> ptc                                                                                                                                             18:04:00
Traceback (most recent call last):
  File "/usr/local/bin/ptc", line 9, in <module>
    load_entry_point('PTCAccount==1.2.0', 'console_scripts', 'ptc')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/ptcaccount/__init__.py", line 1, in <module>
    from ptcaccount.accountcreator import *
  File "/usr/local/lib/python2.7/site-packages/ptcaccount/accountcreator.py", line 14, in <module>
    from ptcaccount.exceptions import *
ImportError: No module named exceptions`

**Comment by xneo64** [comment]
@jepayne1138 
code in accountcreator.py imports ptcaccount.exceptions, while the file is named ptcexceptions.py

I changed the import in accountcreator.py to reflect the different name. This should be a 30sec fix :)

**Comment by jepayne1138** [comment]
Hmm, that's my bad screwing up the version control. It looks like it's actually correct in an old version. I'm not the most experienced and have been working on like four branches on two machines.  I'll take a look and see if I can't straighten it out.

**Comment by jepayne1138** [comment]
Alright, I think I sorted it out and fixed the import with release v1.2.1.  Hopefully I didn't break anything else this time.
