### ISSUE TITLE
CodeException:500

### ISSUE THREAD

**Issue by Trainnnnn** [jepayne1138/PTCAccount#8]
Issue when running the ptc command.

Traceback (most recent call last):
  File "C:\Python27\Scripts\ptc-script.py", line 9, in <module>
    load_entry_point('PTCAccount==1.2.1', 'console_scripts', 'ptc')()
  File "c:\python27\lib\site-packages\ptcaccount\console.py", line 45, in entry
    args.username, args.password, args.email, args.email_tag
  File "c:\python27\lib\site-packages\ptcaccount\accountcreator.py", line 379, in random_account
    try_username, password, try_email
  File "c:\python27\lib\site-packages\ptcaccount\accountcreator.py", line 226, in create_account
    resp_code=200
  File "c:\python27\lib\site-packages\ptcaccount\accountcreator.py", line 88, in request
    raise PTCInvalidStatusCodeException(str(resp.status_code))
ptcaccount.ptcexceptions.PTCInvalidStatusCodeException: 500

**Comment by Trainnnnn** [comment]
Python 2.7

**Comment by Trainnnnn** [comment]
I had an extra space or something.
