### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tonygils** [jepayne1138/PTCAccount#9]
hi guys,

i got this error. can anyone help me?

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ptc", line 9, in <module>
    load_entry_point('PTCAccount==1.2.1', 'console_scripts', 'ptc')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptcaccount/console.py", line 45, in entry
    args.username, args.password, args.email, args.email_tag
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptcaccount/accountcreator.py", line 379, in random_account
    try_username, password, try_email
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptcaccount/accountcreator.py", line 226, in create_account
    resp_code=200
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptcaccount/accountcreator.py", line 88, in request
    raise PTCInvalidStatusCodeException(str(resp.status_code))
ptcaccount.ptcexceptions.PTCInvalidStatusCodeException: 500

**Comment by pozimonte** [comment]
Same issue, script was working 6 hours ago, no changes on my end since then. Other scripts are also returning errors, I'm thinking PTC is blocking requests, but who knows. Waiting patiently.

**Comment by Ashex** [comment]
I tweaked the exception to print the content and pulled this out of it:

> With the exciting launch of Pokémon GO, there’s an overwhelming demand for access to Pokémon Trainer Club accounts, including new accounts, profile changes, and password/username retrieval. Our team is hard at work improving support for these features. Until the work is complete, for a brief time, we’ll be limiting the amount of access to these features. Please refresh your browser and try again.

https://club.pokemon.com/us/pokemon-trainer-club/sign-up/
